// pruebas/01-reading-list/MaximilianoLeonel23/src/components/Book.tsx
import React, { useState } from "react";
import { IBook } from "../types/books";
import BookModal from "./BookModal";
interface Props {
  book: IBook;
  isInMyList: boolean;
  addToMyList: (book: IBook) => void;
  removeFromMyList: (book: IBook) => void;
}
const Book: React.FC<Props> = ({
  book,
  isInMyList,
  addToMyList,
  removeFromMyList,
}) => {
  const { title, author, cover } = book.book;
  const [openModal, setOpenModal] = useState<boolean>(false);
  return (
    <div>
      <article>
        <div className="group flex flex-col gap-4">
          <div className="relative">
            <div className="w-full h-full">
              <img
                src={cover}
                alt={title}
                className="w-full h-full object-center cursor-pointer"
                onClick={() => {
                  if (isInMyList) {
                    setOpenModal(openModal);
                  } else {
                    setOpenModal(!openModal);
                  }
                }}
              />
            </div>
            <div className="grid place-items-center absolute p-2 opacity-0 bottom-0 left-0 right-0 group-hover:opacity-100 transition duration-500">
              {isInMyList ? (
                <button
                  className="bg-primary-green text-sm text-center py-1.5 px-4 rounded w-full z-10"
                  onClick={() => removeFromMyList(book)}
                >
                  Remove
                </button>
              ) : (
                <button
                  className="bg-primary-green text-sm text-center py-1.5 px-4 rounded w-full z-10"
                  onClick={() => addToMyList(book)}
                >
                  Add
                </button>
              )}
            </div>
          </div>
          <div className="flex flex-col text-stone-800 text-center">
            <h4 className="font-medium text-lg">{title}</h4>
            <p className="text-sm">{author.name}</p>
          </div>
        </div>
      </article>
      <BookModal
        openModal={openModal}
        setOpenModal={setOpenModal}
        book={book}
      />
    </div>
  );
};

export default Book;

// pruebas/01-reading-list/david-ponc/src/lib/components/book.svelte
<script lang="ts">
	import { addToReadingList } from '~/lib/stores/library.store';
	import type { Book } from '~/lib/types';
	import { cn } from '~/lib/utils';
	import { BookmarkIcon } from './ui/icons';

	export let book: Book;
</script>

<article class="group flex max-w-[16rem] flex-col gap-2">
	<header class="flex items-start justify-between gap-2">
		<div class="truncate">
			<p class="truncate text-lg font-semibold" title={book.title}>{book.title}</p>
			<p class="italic text-gray-400">{book.genre}</p>
		</div>
		<button
			aria-label="Agregar a lista de lectura"
			on:click={() => addToReadingList(book)}
			class={cn(
				'rounded-md bg-slate-800 p-1.5 text-slate-500 shadow-sm',
				'transition-all duration-100 active:translate-y-px active:scale-x-[.98] active:scale-y-[.98] active:ring-0',
				'hover:text-sky-200 focus:text-sky-200'
			)}
		>
			<BookmarkIcon class="h-5 w-5" />
		</button>
	</header>
	<figure class="relative aspect-[3/4] w-full overflow-hidden rounded-lg bg-slate-900/50">
		<img
			src={book.cover}
			alt={`Cover of ${book.title}`}
			class={cn(
				'h-full w-full object-cover transition-transform',
				'group-hover:scale-105 group-hover:object-center',
				'group-focus:scale-105'
			)}
		/>
	</figure>
	<footer>
		<section class="mb-2 grid grid-cols-3">
			<p class="col-span-2 font-medium text-gray-400">{book.author.name}</p>
			<p class="text-right text-sm font-medium text-gray-400">{book.year}</p>
		</section>
		<p class="line-clamp-2 text-sm font-medium text-gray-500">{book.synopsis}</p>
	</footer>
</article>
