// pruebas/01-reading-list/marceloag/src/components/Booklist.jsx
import Book from './Book';
import Filters from './Filters';
import { AnimatePresence, Reorder } from 'framer-motion';

function Booklist({ books }) {
  return (
    <div className="w-7/12 flex flex-col p-2">
      <Filters />
      <span className='text-slate-500 text-sm font-light'>Libros disponibles {books.length}</span>
      <section className=" [&>ul]:grid [&>ul]:grid-cols-2 [&>ul]:md:grid-cols-3 [&>ul]:xl:grid-cols-4 [&>ul]:gap-2">
        <Reorder.Group axis="x" values={books}>
          <AnimatePresence>
            {books.map((bookData) => (
              <Reorder.Item
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                key={bookData.ISBN}
              >
                <Book {...bookData} />
              </Reorder.Item>
            ))}
          </AnimatePresence>
        </Reorder.Group>
      </section>
    </div>
  );
}

export default Booklist;

// pruebas/01-reading-list/david-ponc/src/lib/components/book-list.svelte
<script lang="ts">
	import type { Library } from '~/lib/types';
	import Book from './book.svelte';
	import { BookOpenIcon } from './ui/icons';

	export let books: Library;
</script>

{#if books.length <= 0}
	<section class="flex flex-col items-center justify-center gap-4 p-8">
		<BookOpenIcon class="h-16 w-16 text-gray-800" />
		<p class="text-2xl font-medium text-gray-500">No se encontraron libros</p>
	</section>
{:else}
	<section class="grid grid-cols-books justify-items-center gap-8 lg:justify-items-start">
		{#each books as book}
			<Book book={book.book} />
		{/each}
	</section>
{/if}
