// pruebas/01-reading-list/iivvaannxx/src/features/library/components/book.svelte
<script lang='ts' context='module'>

  import type { Book } from '$types'
  import { InfoIcon } from '$assets/icons'

</script>

<script lang='ts'>

  // Export all the properties of the Book type.
  export let {

    title, pages, genre,
    cover, synopsis, year,
    ISBN, author

  } = { } as Book

</script>

<div class="relative flex flex-col w-full aspect-cover shadow-sm rounded-xl group">

  <img class="w-full h-full rounded-xl" src={cover} alt={title} />

  <div class='absolute h-full w-full'>
    <div class='h-full w-full bg-black rounded-xl opacity-0 transition-opacity duration-300 group-hover:opacity-40'></div>
  </div>

  <div class='absolute flex items-center justify-center h-full w-full'>

    <button class='w-10 h-10 rounded-full flex items-center justify-center  transition-all duration-300 bg-white opacity-0 group-hover:opacity-100 hover:bg-black hover:text-white'>
      <InfoIcon />
    </button>

  </div>

</div>

// pruebas/01-reading-list/MaximilianoLeonel23/src/components/Book.tsx
import React, { useState } from "react";
import { IBook } from "../types/books";
import BookModal from "./BookModal";
interface Props {
  book: IBook;
  isInMyList: boolean;
  addToMyList: (book: IBook) => void;
  removeFromMyList: (book: IBook) => void;
}
const Book: React.FC<Props> = ({
  book,
  isInMyList,
  addToMyList,
  removeFromMyList,
}) => {
  const { title, author, cover } = book.book;
  const [openModal, setOpenModal] = useState<boolean>(false);
  return (
    <div>
      <article>
        <div className="group flex flex-col gap-4">
          <div className="relative">
            <div className="w-full h-full">
              <img
                src={cover}
                alt={title}
                className="w-full h-full object-center cursor-pointer"
                onClick={() => {
                  if (isInMyList) {
                    setOpenModal(openModal);
                  } else {
                    setOpenModal(!openModal);
                  }
                }}
              />
            </div>
            <div className="grid place-items-center absolute p-2 opacity-0 bottom-0 left-0 right-0 group-hover:opacity-100 transition duration-500">
              {isInMyList ? (
                <button
                  className="bg-primary-green text-sm text-center py-1.5 px-4 rounded w-full z-10"
                  onClick={() => removeFromMyList(book)}
                >
                  Remove
                </button>
              ) : (
                <button
                  className="bg-primary-green text-sm text-center py-1.5 px-4 rounded w-full z-10"
                  onClick={() => addToMyList(book)}
                >
                  Add
                </button>
              )}
            </div>
          </div>
          <div className="flex flex-col text-stone-800 text-center">
            <h4 className="font-medium text-lg">{title}</h4>
            <p className="text-sm">{author.name}</p>
          </div>
        </div>
      </article>
      <BookModal
        openModal={openModal}
        setOpenModal={setOpenModal}
        book={book}
      />
    </div>
  );
};

export default Book;
