// pruebas/01-reading-list/pipegoods/src/components/BookItem.tsx
import { useBookContext } from '../store/useBookContext';
import { Book } from '../types/types';

export default function BookItem({ book }: { book: Book }) {
    const { addBookToRead } = useBookContext();

    return (
        <article onClick={() => addBookToRead(book)}>
            <img
                className="aspect-[1/1.5] h-full object-cover w-full max-w-full rounded hover:opacity-80 transition-opacity duration-300 cursor-pointer"
                src={book.cover}
                alt={`Portada del libro ${book.title}`}
            />
        </article>
    );
}

// pruebas/01-reading-list/diego-gonzales/src/app/components/book-item/book-item.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { Book } from '~/interfaces/books.interface';

@Component({
  selector: 'app-book-item',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './book-item.component.html',
})
export class BookItemComponent {
  @Input({ required: true }) book!: Book;
}

<div
  class="card card-compact w-full bg-neutral text-neutral-content transition-all hover:contrast-75 cursor-pointer rounded"
>
  <div class="card-body items-center text-center">
    <figure>
      <img
        [src]="book.cover"
        [alt]="'Book of ' + book.title"
        class="aspect[310/460] w-full h-full object-contain rounded"
      />
    </figure>
    <h2>{{ book.title }}</h2>
  </div>
</div>
