// pruebas/01-reading-list/genaroibc/src/components/BooksList.tsx
import { component$, type PropFunction } from "@builder.io/qwik"
import type { Book, BookISBN } from "~/types"
import { BookCard } from "./shared/BookCard"

type Props = {
  books: Book[]
  onBookSelect: PropFunction<(BookISBN: BookISBN) => void>
}

export const BooksList = component$(({ books, onBookSelect }: Props) => {
  return (
    <section class="grid grid-cols-[repeat(auto-fill,minmax(min(100%,200px),1fr))] gap-12">
      {books.map(book => (
        <button
          key={book.ISBN}
          onClick$={() => onBookSelect(book.ISBN)}
          class="w-full h-full rounded-md"
        >
          <BookCard {...book} />
        </button>
      ))}
    </section>
  )
})

// pruebas/01-reading-list/jhoneduard26/src/components/BooksList.tsx
import { BookLayout } from '../layouts/BookLayout'
import { BookItem } from './'
import { type Book } from '../types'

interface Props {
  books: Book[]
}

export const BooksList = ({ books }: Props) => {
  return (
    <section className="grid grid-cols-2 gap-6 justify-items-center md:grid-cols-3 lg:grid-cols-4">
      {
        books.map((book) => (
          <BookLayout key={book.ISBN} book={book}>
            <BookItem book={book} />
          </BookLayout>
        ))
      }
    </section>
  )
}
