// pruebas/01-reading-list/ivanatias/src/components/books-list.tsx
import { memo } from 'react'
import BookCard from '@/components/book-card'
import type { BooksList as BooksListType } from '@/utils/books'

export interface Props {
  books: BooksListType
  className?: string
}

const defaultStyle =
  'grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4'

const BooksList = memo(function BooksList({ books, className }: Props) {
  return (
    <ul className={className ?? defaultStyle}>
      {books.map(book => (
        <li key={book.ISBN}>
          <BookCard book={book} />
        </li>
      ))}
    </ul>
  )
})

export default BooksList

// pruebas/01-reading-list/genaroibc/src/components/BooksList.tsx
import { component$, type PropFunction } from "@builder.io/qwik"
import type { Book, BookISBN } from "~/types"
import { BookCard } from "./shared/BookCard"

type Props = {
  books: Book[]
  onBookSelect: PropFunction<(BookISBN: BookISBN) => void>
}

export const BooksList = component$(({ books, onBookSelect }: Props) => {
  return (
    <section class="grid grid-cols-[repeat(auto-fill,minmax(min(100%,200px),1fr))] gap-12">
      {books.map(book => (
        <button
          key={book.ISBN}
          onClick$={() => onBookSelect(book.ISBN)}
          class="w-full h-full rounded-md"
        >
          <BookCard {...book} />
        </button>
      ))}
    </section>
  )
})
