// pruebas/02-bazar-universal/fernandochaza/simple-shop/src/app/page.tsx
import SearchBar from "../components/SearchBar"

export default function Home() {
  return (
    <main className="h-screen min-h-fit flex flex-col place-content-center bg-slate-100">
      <h1 className="mb-12 text-4xl font-extrabold text-center text-slate-800">
        SIMPLE SHOP
      </h1>
      <SearchBar />
    </main>
  )
}

// pruebas/01-reading-list/sbetav/src/App.vue
<script setup lang="ts">
import ReadingBooks from "./components/ReadingBooks.vue"
import AvailableBooks from "./components/AvailableBooks/AvailableBooks.vue";
import Filters from "./components/Filters/Filters.vue";
</script>

<template>
     <main
          class="bg-bg flex flex-col justify-center items-center text-text py-16 gap-8 px-8 md:flex-row md:items-stretch md:h-screen">
          <div class="flex flex-col max-w-3xl w-full">
               <Filters />
               <AvailableBooks />
          </div>
          <ReadingBooks />
     </main>
</template>
