// pruebas/01-reading-list/erik19970805/src/app/book/[id]/page.tsx
import { Button } from '@components/Button';
import { Header } from '@components/Header';
import { libraryData } from '@data/library';

interface Props {
  params: { id: string };
}

export default function BookDetail({ params: { id } }: Props) {
  const book = libraryData.find(({ book }) => book.ISBN === id)?.book;
  if (!book) return <h1>Book not found</h1>;
  return (
    <>
      <Header />
      <main className="grid items-center p-8">
        <div className="flex flex-col gap-8 m-auto items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-6xl dark:border-gray-700 dark:bg-gray-800 p-4">
          <img
            alt={book.title}
            src={book.cover}
            className="object-cover rounded-t-lg rounded-lg max-h-[500px]"
          />
          <div className="flex flex-col gap-4">
            <p className="text-3xl">
              <strong className="text-white">Título:</strong>&nbsp;
              <span className="text-gray-400">{book.title}</span>
            </p>
            <p className="text-3xl">
              <strong className="text-white">Autor:</strong> &nbsp;
              <span className="text-gray-400">{book.author.name}</span>
            </p>
            <div className="flex gap-3 items-center flex-wrap">
              <strong className="text-xl text-white whitespace-nowrap">Otros libros del autor:&nbsp;</strong>
              <div className="flex flex-wrap gap-2">
                {book.author.otherBooks.length > 0 ? (
                  book.author.otherBooks.map((item) => (
                    <span
                      className="bg-purple-100 text-purple-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-purple-900 dark:text-purple-300"
                      key={item}
                    >
                      {item}
                    </span>
                  ))
                ) : (
                  <span className="text-yellow-500">No hay otros libros del autor</span>
                )}
              </div>
            </div>
            <p className="text-lg">
              <strong className="text-white">Género:</strong>&nbsp;
              <span className="text-gray-400">{book.genre}</span>
            </p>
            <p className="text-lg">
              <strong className="text-white">Sinopsis:</strong>&nbsp;
              <span className="text-gray-400">{book.synopsis}</span>
            </p>
            <p className="text-lg">
              <strong className="text-white">ISBN:</strong>&nbsp;
              <span className="text-gray-400">{book.ISBN}</span>
            </p>
            <p className="text-lg">
              <strong className="text-white">Año de publicación:</strong>&nbsp;
              <span className="text-gray-400">{book.year}</span>
            </p>
            <p className="text-lg">
              <strong className="text-white">Páginas:</strong>&nbsp;
              <span className="text-gray-400">{book.pages}</span>
            </p>
            <Button
              className=" max-w-xs focus:outline-none text-white whitespace-nowrap bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900"
              book={book}
            />
          </div>
        </div>
      </main>
    </>
  );
}

// pruebas/01-reading-list/FrM-bot/src/routes/book/[id]/+page.svelte
<script lang="ts">
  import { fly, slide } from 'svelte/transition';
  import ButtonBookmark from '$lib/components/buttonBookmark.svelte'
  import Image from '$lib/components/image.svelte'
  import SectionSubTitleCard from '$lib/components/sectionSubTitleCard.svelte'
  import SubSection from '$lib/components/subSection.svelte'
  import { LocalRotes } from '$lib/utils/routes'
  import type { PageData } from './$types'
  import { onMount, onDestroy } from 'svelte'

  export let data: PageData
  $: ({ book } = data)
  onMount(() => {
    const header = globalThis.document.querySelector('#main-header')
    if (globalThis?.window?.scrollY === 0 && header?.classList.contains('main-header')) {
      header?.classList.remove('main-header')
    }
    globalThis.window.onscroll = (e) => {
      if (globalThis?.location.pathname === LocalRotes.book.details(data.book.ISBN)) {
        if (globalThis?.window?.scrollY >= 10 && !header?.classList.contains('main-header')) {
          header?.classList.add('main-header')
        }
        if (globalThis?.window?.scrollY === 0 && header?.classList.contains('main-header')) {
          header?.classList.remove('main-header')
        }
      }
    }
  })
  onDestroy(() => {
    const header = globalThis.document?.querySelector('#main-header')
    header?.classList.add('main-header')
  })
</script>

<svelte:head>
  <title>{book.title}</title>
</svelte:head>

<div
  class="absolute w-full h-[450px] left-0 top-0 -z-[1] blur-sm"
  style={`background: linear-gradient(to top, rgba(20, 20, 20, 1), rgba(20, 20, 20, .9), rgba(20, 20, 20, .8), rgba(20, 20, 20, .7), rgba(20, 20, 20, .6)), url("${book.cover}") no-repeat 0%/0%;background-size: cover;background-position: center 10%;`}
  transition:slide={{ duration: 200, delay: 100, axis: 'y' }}
/>
<section
  class="grid sm:grid-cols-[minmax(80px,300px)_1fr] grid-cols-1 sm:items-end items-center"
  transition:fly={{ x: -200, duration: 200 }}
>
  <!-- <div class="backdrop-blur [box-shadow:inset_0px_0px_120px_150px_rgba(20_20_20_/_1);]"> -->
  <div class="[--opacity:0] relative hover:[--opacity:1]">
    <Image src={book.cover} alt={book.title} class="max-w-sm shadow-lg shadow-tertiary/20 w-full" />
    <div
      class="absolute z-[1] rounded inset-1 flex justify-center items-center opacity-[var(--opacity)] duration-200"
    >
      <div class="flex flex-col items-center">
        <ButtonBookmark
          book={{
            id: book.ISBN,
            title: book.title,
            author: book.author.name,
            cover: book.cover,
            genre: book.genre,
            pages: book.pages
          }}
        />
      </div>
    </div>
  </div>
  <div class="flex flex-col justify-end w-full">
    <div
      class="mb-8 mt-5 bg-gradient-to-r from-tertiary/80 to-transparent p-2 border-l rounded-r-sm w-full"
    >
      <h1 class="text-2xl font-semibold">{book.title}</h1>
      <span>{book.genre}</span>
      <h3 class="text-xs">{book.author.name}</h3>
    </div>
  </div>
  <!-- </div> -->
</section>
<section
  class="grid sm:grid-cols-[minmax(80px,300px)_1fr] grid-cols-1 md:mt-8 md:gap-0 gap-4"
  transition:fly={{ y: -200, duration: 200 }}
>
  <div class="flex flex-col gap-4">
    <SubSection title="Páginas" description={book.pages} />
    <SubSection title="Ano" description={book.year} />
    <SubSection title="Género" description={book.genre} />
    <SubSection title="Autor" description={book.author.name} />
    <SubSection title="Libros">
      {#each data?.book.author.otherBooks as book}
        <span class="bg-gradient-to-r from-tertiary to-transparent p-2 border-l">{book}</span>
      {/each}
    </SubSection>
  </div>
  <div class="flex flex-col gap-4">
    <SectionSubTitleCard>Synopsis</SectionSubTitleCard>
    <p>{book.synopsis}</p>
  </div>
</section>
