// pruebas/01-reading-list/cmollinea/reading-list-main/src/Componets/Header.jsx
function Header() {
  return (
    <header className='z-10'>
      <h1 className="pt-6 relative text-4xl w-full font-bold text-center after:content-[''] after:absolute after:w-full after:h-6 after:bg-sky-600/40 after:left-0 after:-bottom-1 after:-z-10">
        Catálogo de Libros.
      </h1>
    </header>
  );
}

export default Header;

// pruebas/01-reading-list/oscarprdev/src/core/components/Header.svelte
<script>
  import Nav from './Nav.svelte'
</script>

<header
  class="relative flex items-center justify-between h-[100px] p-2 border-b-2 border-b-nav text-primary gap-5 bg-light xl:h-screen xl:w-[100px] xl:p-1 xl:border-none"
>
  <span class="text-2xl font-bold ml-2 xl:absolute xl:top-3 xl:left-3 xl:ml-0"
    ><i>Books</i></span
  >
  <Nav />
</header>
