// pruebas/01-reading-list/maxiCalderonBuono/src/components/BookCard.svelte
<script lang="ts">
	import { longpress } from '$lib/helpers/longPress';
	import type { Book } from '../types';
	import Icon from '@iconify/svelte';
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();

	function updateWishlist() {
		dispatch('update');
	}

	function goToDetail() {
		dispatch('navigate');
	}

	export let book: Book;
	export let cta: string;
</script>

<div class="flex flex-col overflow-hidden" use:longpress on:long>
	<button class="relative overflow-hidden group rounded-2xl" on:click={goToDetail}>
		<div class="absolute left-0 top-0 h-16 w-16">
			<div
				class="absolute z-10 transform -rotate-45 bg-blue-200/90 text-center text-gray-800 font-semibold py-1 left-[-34px] top-[32px] w-[170px]"
			>
				{book.genre}
			</div>
		</div>
		<img
			class={`h-[350px] w-full group-hover:scale-125 transition-all ease-in-out delay-75`}
			src={book.cover}
			alt="Cover for {book.title}"
		/>
	</button>
	<div class="flex justify-between mt-2 relative">
		<div class="flex flex-col">
			<strong>{book.title}</strong>
			<span>{book.author.name}</span>
		</div>
		<span
			class="bg-green-100 absolute right-0 bottom-0 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300"
			>Pages: {book.pages}</span
		>
	</div>
	<button
		class="btn variant-filled font-bold rounded-lg p-2 mx-auto mt-3 hover:bg-indigo-300"
		on:click={updateWishlist}
		><Icon icon="icon-park:list" />
		<span>{cta}</span>
	</button>
</div>

// pruebas/01-reading-list/genaroibc/src/components/shared/BookCard.tsx
import { component$ } from "@builder.io/qwik"
import type { Book } from "~/types"
import {
  IconBookOutlined,
  IconBookmarkFilled,
  IconBookmarkPlus,
  IconCalendarOutlined
} from "~/components/shared/Icons"

export const BookCard = component$(
  ({ cover, genre, isInReadingList, pages, title, year, author }: Book) => {
    return (
      <article class="aspect-[1/1.6] group hover:shadow-lg transition-transform duration-300 ease-in-out text-white relative bg-black rounded-md">
        <div class="relative overflow-hidden rounded-tl-md rounded-tr-md">
          <BookBadge isInReadingList={isInReadingList} />

          <img
            src={cover}
            alt={title}
            width={300}
            height={500}
            class="brightness-95 grayscale-[0.3] group-hover:grayscale-0 group-hover:brightness-110 transition-all duration-300 aspect-[1/1.4] group-hover:scale-110"
          />

          <ul class="absolute bottom-0 flex items-center justify-between gap-4 w-full py-1.5 px-3 bg-black/60 text-gray-200">
            <li class="whitespace-nowrap truncate max-w-full text-xs flex items-center gap-1">
              <IconBookOutlined /> {pages}
            </li>

            <li class="whitespace-nowrap truncate max-w-full text-xs flex items-center gap-1">
              <IconCalendarOutlined />
              {year}
            </li>
          </ul>
        </div>

        <div class="p-4">
          <h6 class="whitespace-nowrap truncate max-w-full my-2 font-bold text-base text-left">
            {title}
          </h6>

          <p class="whitespace-nowrap truncate max-w-full my-2 font-medium text-sm text-left">
            {author.name}
          </p>

          <span class="whitespace-nowrap truncate px-2 py-1 block mt-4 bg-gray-800 text-gray-400 rounded-xl text-xs w-fit">
            {genre.toLocaleLowerCase()}
          </span>
        </div>
      </article>
    )
  }
)

type BadgeProps = {
  isInReadingList: boolean
}

const BookBadge = component$(({ isInReadingList }: BadgeProps) => {
  return (
    <section
      aria-hidden={true}
      class="bg-black/50 p-2 absolute top-1 right-1 z-20 rounded-full"
    >
      {isInReadingList ? (
        <IconBookmarkFilled size={32} />
      ) : (
        <IconBookmarkPlus size={32} />
      )}
    </section>
  )
})
