// pruebas/01-reading-list/iivvaannxx/src/features/library/components/header.svelte
<script lang='ts' context='module'>

  import { LAYOUTS } from '../lib/constants'
  import SwitchLayoutButton from './switchers/layout-button.svelte'

</script>

<header class='h-16 w-full px-16 flex items-center justify-between'>

  <h2 class='text-xl font-light'>
    <slot />
  </h2>

  <div class='flex items-center justify-center'>

    {#each LAYOUTS as layoutType}
      <SwitchLayoutButton type={ layoutType } />
    {/each}

  </div>

</header>

<hr class='mx-16 mt-4' />

// pruebas/01-reading-list/facindito/src/components/Header.jsx
import { useWishlistContext } from '../context/listBookContext'
import { Button } from './button'

export function Header ({ handleChange, showSection }) {
  const { wishlist } = useWishlistContext()

  return (
    <header className='max-w-6xl mx-auto p-4 flex flex-wrap gap-4 justify-between items-center'>
      <h1 className='font-bold text-2xl'>My Book List</h1>
      {
        showSection === 'Home' && (
          <Button
            handleChange={handleChange}
            wishlist={wishlist}
          >
            Wishlist
          </Button>
        )
      }
      {
        showSection === 'Wishlist' && (
          <Button
            handleChange={handleChange}
          >
            Catálogo
          </Button>
        )
      }
    </header>
  )
}
