// pruebas/01-reading-list/oscarprdev/src/core/components/Header.svelte
<script>
  import Nav from './Nav.svelte'
</script>

<header
  class="relative flex items-center justify-between h-[100px] p-2 border-b-2 border-b-nav text-primary gap-5 bg-light xl:h-screen xl:w-[100px] xl:p-1 xl:border-none"
>
  <span class="text-2xl font-bold ml-2 xl:absolute xl:top-3 xl:left-3 xl:ml-0"
    ><i>Books</i></span
  >
  <Nav />
</header>

// pruebas/01-reading-list/facindito/src/components/Header.jsx
import { Link } from 'react-router-dom'
import { BookIcon } from './icons'
import { useWishlistContext } from '../context/listBookContext'

export function Header () {
  const { wishlist } = useWishlistContext()

  return (
    <header className='max-w-6xl mx-auto p-4 flex justify-between items-center'>
      <Link to='/' className='font-bold text-2xl'>My Book List</Link>
      <Link to='/wishlist' className='relative'>
        <BookIcon />
        {
          wishlist.length > 0 && (
            <div
              className='w-4 h-4 absolute flex justify-center items-center rounded-full bg-rhino-500 top-0 right-0 text-white text-[10px]'
            >
              {wishlist.length}
            </div>
          )
        }
      </Link>
    </header>
  )
}
