// pruebas/01-reading-list/josevc997/components/Book/Item.vue
<script setup lang="ts">
import { Book } from "../../types/books";
import { PropType } from "vue";

const props = defineProps({
  book: {
    type: Object as PropType<Book>,
    required: true,
  },
});
</script>
<template>
  <div
    class="border rounded-lg grid place-content-between grid-cols-1 relative cursor-pointer hover:shadow-2xl transition-all duration-300 ease-in-out"
  >
    <div
      class="absolute h-full w-full hover:bg-slate-900/60 flex justify-center items-center text-base font-bold rounded-lg transition-all duration-500 ease-in-out text-white hover:text-white text-transparent"
    >
      <p class="text-center">Agregar a lista</p>
    </div>
    <!-- <div class="pb-2">
      <h1 class="text-xl font font-medium">{{ book.book.title }}</h1>
      <p class="text-sm text-gray-500">{{ book.book.author.name }}</p>
    </div> -->
    <div class="aspect-[9/16] w-full">
      <img
        :src="book.book.cover"
        :alt="book.book.title"
        class="rounded-md object-cover h-full w-full"
      />
    </div>
  </div>
</template>

// pruebas/01-reading-list/iivvaannxx/src/features/library/components/layouts/grid/item.svelte
<script lang='ts' context='module'>

  import { PrimaryButton } from '$lib/components'
  import { addBook, currentListName } from '$features/booklist'

</script>

<script lang='ts'>

  /** @brief The exposed data of the book. */
  export let bookData: Book

</script>

<article class='relative flex flex-col w-80 aspect-cover rounded-xl items-center'>

  <div class='w-full h-full relative group duration-300'>

    <img class='w-full h-full rounded-xl transition duration-300 group-hover:cursor-pointer group-hover:grayscale group-hover:brightness-75' src={ bookData.cover } alt={ bookData.title } />

    <div class='flex opacity-0 w-[12rem] max-w-[15rem] min-w-[10rem] absolute transition duration-300 top-1/2 left-1/2 justify-center items-center group-hover:opacity-100 -translate-y-1/2 -translate-x-1/2'>

      <PrimaryButton onClick={ () => { addBook($currentListName, bookData) } } extraClasses='w-3/4 h-12'>
        <span class='text-lg flex-grow text-center uppercase'>Añadir</span>
      </PrimaryButton>

    </div>

  </div>

  <h4 class='text-primary-500 font-bold text-lg text-center mt-6 truncate'>{ bookData.title }</h4>
  <h6 class='uppercase text-base font-normal text-center mt-1'>{ bookData.author.name }</h6>

</article>
