// pruebas/01-reading-list/oscarprdev/src/core/components/BookModal.svelte
<script lang="ts">
  import { modalState } from '../store/modal-store'
  import { XIcon } from 'svelte-feather-icons'
  import { BookOpenIcon } from 'svelte-feather-icons'

  const closeModal = () => {
    modalState.update((state) => ({ isOpen: false, book: null }))
  }
</script>

{#if $modalState.isOpen}
  <dialog
    open={$modalState.isOpen}
    data-modal-target="modal"
    class="absolute top-0 left-0 bg-dark backdrop-blur-sm w-full h-full grid place-items-center z-1 open:animate-fade-in open:backdrop:animate-fade-in"
  >
    <article
      class="flex items-start justify-center gap-8 p-8 bg-light max-w-xl max-h-800 rounded-sm relative"
    >
      <button
        class="absolute top-3 right-3 z-10 cursor-pointer"
        on:click={closeModal}
      >
        <XIcon size="24" />
      </button>
      <section class="h-80 shadow-[4.0px_5.0px_8.0px_rgba(0,0,0,0.38)]">
        <img
          class="w-full h-full object-cover"
          src={$modalState.book.cover}
          alt={$modalState.book.title}
        />
      </section>
      <section class="relative w-1/2 h-80 flex flex-col gap-5 p-5">
        <div class="flex flex-col gap-3">
          <h2 class="text-lg"><b>{$modalState.book.title}</b></h2>
          <h3 class="text-sm">
            <i>{$modalState.book.author.name} - {$modalState.book.year}</i>
          </h3>
          <span
            class="py-1.5 px-5 w-fit rounded-full bg-overlayModal text-sm text-light"
            >{$modalState.book.genre}</span
          >
          <p><i>{$modalState.book.synopsis}.</i></p>
        </div>
        <button
          class="absolute bottom-3 px-5 py-2 rounded-3xl bg-overlayModal cursor-pointer self-center hover:bg-nav duration-300"
          ><BookOpenIcon size="25" class="text-light" /></button
        >
      </section>
    </article>
  </dialog>
{/if}

// pruebas/01-reading-list/src/components/BookModal.tsx
import React from "react";
import { IBook } from "../types/books";

interface Props {
  openModal: boolean;
  setOpenModal: React.Dispatch<React.SetStateAction<boolean>>;
  book: IBook;
}

const BookModal: React.FC<Props> = ({ openModal, setOpenModal, book }) => {
  const { title, ISBN, author, cover, genre, pages, synopsis, year } =
    book.book;
  return (
    <div
      className={`${
        openModal ? "flex" : "hidden"
      }  fixed top-0 left-0 w-full h-full justify-center items-center z-20`}
    >
      <div
        className="fixed top-0 left-0 w-full h-full bg-stone-900 opacity-30"
        onClick={() => setOpenModal(!openModal)}
      ></div>
      <article className="relative z-30 bg-stone-50 rounded max-w-[40rem] h-[30rem]">
        <div className="flex items-start w-full h-full">
          <div className="w-1/2 h-full">
            <img src={cover} className="w-full h-full rounded" alt={title} />
          </div>
          <div className="w-1/2 h-full relative flex flex-col gap-4 p-4 text-stone-800">
            <div>
              <h4 className="font-bold text-2xl">{title}</h4>
              <p className="text-sm">por {author.name}</p>
            </div>
            <p className="text-sm font-light">{synopsis}</p>
            {/* <span className="w-fit text-sm border border-stone-300 bg-stone-200 text-stone-500 rounded px-2 py-0.5">
              {genre}
            </span> */}
            <div className="text-sm border-t border-stone-200 pt-4 rounded">
              <h4 className="font-medium pb-2">Detalles</h4>
              <div className="flex flex-col gap-1">
                <p>
                  ISBN: <span>{ISBN}</span>
                </p>
                <p>
                  Género: <span>{genre}</span>
                </p>
                <p>
                  Páginas: <span>{pages}</span>
                </p>
                <p>
                  Año: <span>{year}</span>
                </p>
              </div>
            </div>
            <button
              className="absolute bottom-0 right-0 p-4 text-sm"
              onClick={() => setOpenModal(!openModal)}
            >
              Cerrar
            </button>
          </div>
        </div>
      </article>
    </div>
  );
};

export default BookModal;
