// pruebas/02-bazar-universal/diego-gonzales/src/routes/items/[id]/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$, type DocumentHead } from '@builder.io/qwik-city';
import { getRating } from '~/helpers/getRating';
import { type ErrorResponse } from '~/interfaces/error-response.interface';
import type { Product } from '~/interfaces/products-response.interface';

export const useProductLoader = routeLoader$(async ({ params, fail }) => {
  const { id } = params;
  const url = `http://localhost:5173/api/items/${id}`;

  const response = await fetch(url);

  if (!response.ok) {
    const { statusCode, message } = (await response.json()) as ErrorResponse;
    return fail(statusCode, { message });
  }

  const data = (await response.json()) as Product;
  return data;
});

export default component$(() => {
  const product: any = useProductLoader();

  if (product.value.message) {
    return (
      <div>
        <h3>{product.value.message}</h3>
      </div>
    );
  }

  return (
    <div class="h-[calc(100vh-80px)] relative">
      <div class="grid gap-5 justify-center items-center justify-items-center">
        <section class="grid gap-4 grid-cols-[3fr_1fr] justify-center items-center justify-items-center">
          <img
            class="rounded-full object-cover w-48 h-48"
            src={product.value.thumbnail}
            alt="Product"
            width={200}
            height={200}
          />
          <ul class="grid gap-2">
            {product.value.images
              .slice(0, 3)
              .map((image: string, index: number) => (
                <li key={index}>
                  <img
                    class="rounded-full object-cover w-16 h-16"
                    src={image}
                    alt={`Image ${index + 1} for ${product.title}`}
                    width={64}
                    height={64}
                  />
                </li>
              ))}
          </ul>
        </section>

        <section class="text-center">
          <h3 class="text-2xl font-bold">{product.value.title}</h3>
          <div class="flex items-center gap-4">
            <p class="flex flex-col">
              <span class="font-bold">{product.value.price}$</span>
              <span class="text-xs">{product.value.stock} disponibles</span>
            </p>
            <p>{getRating({ rating: product.value.rating })}</p>
          </div>
        </section>

        <section class="max-w-md">
          <p>{product.value.description}</p>
        </section>
      </div>

      <div class="absolute bottom-4 md:static md:mt-10 w-full text-center">
        <button class="btn btn-primary w-full max-w-md">Buy</button>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: 'Product',
  meta: [
    {
      name: 'description',
      content: 'Bazar Online product page',
    },
    {
      name: 'keywords',
      content: 'bazar, online, shopping, ecommerce, store, products, buy, sell',
    },
  ],
};

// pruebas/02-bazar-universal/aiv4ro/src/app/items/[id]/page.tsx
import { ProductPrice } from '@/components/ProductPrice'
import { ProductRating } from '@/components/ProductRating'
import { getProduct } from '@/services/get-product'

export default async function Page ({
  params
}: {
  params: {
    id: string
  }
}) {
  const product = await getProduct({ id: params.id })

  const mainImage = product.images[0]
  const otherImages = product.images.slice(1)

  return (
    <section className='flex flex-col justify-center gap-6 mt-5'>
      <header className='flex gap-3 items-center justify-center'>
        <picture className='w-full max-w-[250px] h-auto flex-1 aspect-square overflow-hidden rounded-full'>
          <img className='w-full h-full object-cover' src={mainImage} alt={product.title} />
        </picture>
        <div className='flex flex-col gap-3'>
          {otherImages.map((image, index) => (
            <picture key={index} className='w-16 h-16 overflow-hidden rounded-full'>
              <img className='h-full w-full object-cover' src={image} alt={product.title} />
            </picture>
          ))}
        </div>
      </header>
      <h2 className='text-center text-xl font-semibold'>{product.title} - {product.brand}</h2>
      <div className='flex items-center justify-center gap-5'>
        <div className='flex flex-col text-center'>
          <ProductPrice price={product.price} />
          <span>{product.stock} disponibles</span>
        </div>
        <ProductRating rating={product.rating} />
      </div>
      <p className='text-center'>
        {product.description}
      </p>
      <button className='px-10 py-3 text-xl font-semibold bg-zinc-800 hover:bg-zinc-700 rounded'>
        Comprar
      </button>
    </section>
  )
}
