// pruebas/01-reading-list/gianback/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { Banner } from "~/components";

export default component$(() => {
  return (
    <div>
      <Banner />
    </div>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};

// pruebas/01-reading-list/DavidDeadly/DavBooks/src/routes/+page.svelte
<script lang="ts">
  import { booksStore } from '$lib';
  import Header from '$lib/components/Header.svelte';
  import BooksApp from '$lib/components/BooksApp.svelte';

  export let data;
  let books: IBook[] = data.books;

  let numAvaileblesBooks: number = 0;
  $: numAvaileblesBooks = $booksStore.getNumAvaileblesBooks(books);
</script>

<svelte:head>
  <title>DavBooks</title>
  <meta name="description" content="DavBooks Library" />
</svelte:head>

<Header
  {numAvaileblesBooks}
  on:filteredBooks={({ detail: filteredBooks }) => (books = filteredBooks)}
/>
<BooksApp filteredBooks={books} />
