// pruebas/01-reading-list/mitoral/src/components/Books.jsx
import booksData from '../../../books.json'
import { Book } from './Book'

export function Books () {
  console.log(booksData)
  return (
    <>
      <div className='grid grid-cols-[repeat(auto-fill,minmax(160px,1fr))] gap-5'>
        {
            booksData.library.map((book, index) => {
              return <Book key={index} />
            })
        }
      </div>
    </>
  )
}

// pruebas/01-reading-list/DavidDeadly/DavBooks/src/components/Books.svelte
<script lang="ts">
  import Book from './Book.svelte';

  export let books: IBook[];
  export let booksWidth = '250px';
  export let showBooksInfo = true;
</script>

<ul class="books" style="--booksWidth:{booksWidth}">
  {#each books as book}
    <Book {book} showInfo={showBooksInfo} --booksWidth={booksWidth} />
  {/each}
</ul>

<style>
  .books {
    display: grid;
    gap: 15px;
    grid-template-columns: repeat(auto-fit, minmax(var(--booksWidth), 1fr));
  }
</style>
