// pruebas/01-reading-list/KrlosPK/src/app/library/components/reading-list/reading-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Books } from '../../interfaces/types';

@Component({
  selector: 'library-reading-list',
  templateUrl: './reading-list.component.html',
  styleUrls: ['./reading-list.component.css'],
})
export class ReadingListComponent {
  @Input()
  public readingList: Books[] = [];

  @Output()
  public onRemoveFromReadingList = new EventEmitter<string>();

  public isReadingList: boolean = false;
  toggleReadingList(): void {
    this.isReadingList = !this.isReadingList;
  }
  removeFromReadingList(bookId: string): void {
    this.onRemoveFromReadingList.emit(bookId);
  }
}

<aside class="top-0 left-0 z-10 hidden h-full transition-all md:flex">
  <section
    [ngClass]="{ 'reading-list-overflow': isReadingList }"
    class="min-w-[271px] min-h-screen p-4 bg-secondary-color"
  >
    <h2 class="mb-4 text-xl font-semibold text-center whitespace-nowrap">
      Lista de Lectura
      <span *ngIf="readingList.length > 0"> / </span>
      <span
        [ngClass]="{ active: readingList.length > 0 }"
        *ngIf="readingList.length > 0"
        class="font-semibold min-w-[2ch]"
      >
        {{ readingList.length }}
      </span>
    </h2>

    <h3 *ngIf="readingList.length === 0" class="text-sm opacity-90">
      Aún no hay libros en la lista de lectura
    </h3>

    <div
      class="grid grid-cols-1 gap-2 md:place-items-start place-items-center md:grid-cols-2 md:gap-4"
    >
      <article
        [title]="item.book.title"
        *ngFor="let item of readingList"
        class="relative"
      >
        <button
          (click)="removeFromReadingList(item.book.ISBN)"
          class="absolute top-0 right-0 p-1 transition-colors select-none bg-secondary-color hover:bg-cyan-50 rounded-es-lg"
        >
          <img
            alt="Button to delete"
            height="24"
            src="./assets/icons/x.svg"
            width="24"
          />
        </button>

        <img
          [alt]="item.book.title"
          [src]="item.book.cover"
          class="object-contain last-article-margin"
          height="250"
          width="150"
        />
      </article>
    </div>
  </section>
</aside>

<!-- Responsive Nav -->
<aside
  [ngClass]="{ 'is-reading-list': isReadingList }"
  class="fixed top-0 left-0 z-10 flex h-full transition-all -translate-x-full md:hidden"
>
  <button
    (click)="toggleReadingList()"
    class="absolute flex items-center justify-center gap-1 p-3 transition-colors rounded-r-lg select-none bg-secondary-color md:hidden md:hover:bg-gray-900 left-full w-fit h-fit"
    title="Lista de Lectura"
    type="button"
  >
    <img
      alt="Reading list books"
      height="24"
      class="w-4"
      src="./assets/icons/books.svg"
      width="24"
    />
    <span
      [ngClass]="{ active: readingList.length > 0 }"
      class="font-semibold min-w-[2ch]"
    >
      {{ readingList.length }}
    </span>
  </button>

  <section
    [ngClass]="{ 'reading-list-overflow': isReadingList }"
    class="min-h-screen p-4 bg-secondary-color"
  >
    <h2 class="mb-4 text-xl font-semibold text-center whitespace-nowrap">
      Lista de Lectura
    </h2>

    <h3 *ngIf="readingList.length === 0" class="text-sm opacity-90">
      Aún no hay libros en la lista de lectura
    </h3>

    <div
      class="grid grid-cols-1 gap-2 md:place-items-start place-items-center md:grid-cols-2 md:gap-4"
    >
      <article
        [title]="item.book.title"
        *ngFor="let item of readingList"
        class="relative"
      >
        <button
          (click)="removeFromReadingList(item.book.ISBN)"
          class="absolute top-0 right-0 p-1 transition-colors select-none bg-secondary-color hover:bg-cyan-50 rounded-es-lg"
        >
          <img
            alt="Button to delete"
            height="24"
            src="./assets/icons/x.svg"
            width="24"
          />
        </button>

        <img
          [alt]="item.book.title"
          [src]="item.book.cover"
          class="object-contain last-article-margin"
          height="175"
          width="110"
        />
      </article>
    </div>
  </section>
</aside>

// pruebas/01-reading-list/lace04/book-app/src/components/ReadingList.jsx
import React from 'react';
import { BiSolidMinusSquare } from 'react-icons/bi';

function ReadingList({ books, onRemove }) {
  return (
    <section className='bg-slate-200 dark:bg-gray-900 h-full p-4 rounded-lg mt-10 flex flex-col items-center'>
      <h1 className='text-3xl md:text-4xl text-center font-bold m-5 text-gray-900 dark:text-gray-300'>
        Lista Lectura
      </h1>
      <div className='text-lg md:text-xl mb-4 text-gray-900 dark:text-gray-300'>
        Libros disponibles: {books.length}
      </div>

      <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-1 xl:grid-cols-2'>
        {books.map((book) => (
          <div
            key={book.ISBN}
            className='bg-white dark:bg-gray-800 m-2 flex flex-col justify-center items-center rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 relative lg:max-w-[170px] md:min-w-[130px] md:mr-10 my-4'
          >
            <img
              src={book.cover}
              alt={book.title}
              className='w-32 h-28 object-contain mt-4'
            />
            <h3 className='md:text-xs text-center m-4 h-12 text-gray-900 dark:text-gray-300'>
              {book.title}
            </h3>

            <div className='absolute top-2 right-2'>
              <button onClick={() => onRemove(book)}>
                <BiSolidMinusSquare
                  className='text-red-500 text-2xl'
                  size={32}
                />
              </button>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default ReadingList;
