// pruebas/01-reading-list/sbetav/src/App.vue
<script setup lang="ts">
import ReadingBooks from "./components/ReadingBooks.vue"
import AvailableBooks from "./components/AvailableBooks/AvailableBooks.vue";
import Filters from "./components/Filters/Filters.vue";
</script>

<template>
     <main
          class="bg-bg flex flex-col justify-center items-center text-text py-16 gap-8 px-8 md:flex-row md:items-stretch md:h-screen">
          <div class="flex flex-col max-w-3xl w-full">
               <Filters />
               <AvailableBooks />
          </div>
          <ReadingBooks />
     </main>
</template>

// pruebas/02-bazar-universal/DuffmanCC/app/page.tsx
import { Truck } from "@/components/Icons";
import SearchWithButton from "@/components/SearchWithButton";

export default function Home() {
  return (
    <div className="flex flex-col gap-8 items-center justify-center grow">
      <Truck width="200" />

      <h1 className="text-4xl font-bold">Bazar Online</h1>

      <SearchWithButton />
    </div>
  );
}
