// pruebas/01-reading-list/juanma1989dev/src/lib/components/CardBook.svelte
<script>
    import { createEventDispatcher } from "svelte";
    import BadgeBookDetail from "$lib/components/BadgeBookDetail.svelte"

    export let book
    
    let dispatch = createEventDispatcher();

    function handleClickAddBookToReadingList(book) {
        dispatch("addBookToReadingList", {book});
    }
</script>

<article class="flex flex-col sm:flex-row gap-4 rounded-lg border dark:border-none rounded-lg shadow dark:bg-slate-700 " >
    
    <img class="object-cover rounded-t-lg h-full w-[120px] md:w-[100px] md:rounded-none md:rounded-l-lg " 
        src={ book.cover } alt={book.title}
    >

    <div>
        <h5 class="mb-2 text-xl tracking-tight text-gray-900 dark:text-white">
            {book.title}
            <div class="flex flex-row my-4">
                <BadgeBookDetail>Género: {book.genre}</BadgeBookDetail>
                <BadgeBookDetail>Páginas: {book.pages}</BadgeBookDetail>
            </div>
        </h5>
        
        <p class="mb-3 font-normal text-gray-700 dark:text-white">{book.synopsis}</p>

        <button 
            type="button" 
            class="py-1 px-3 mr-1 mb-1 text-gray-900 focus:outline-none bg-white dark:bg-sky-800 rounded-full border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-300 dark:text-white dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
            on:click={ () => { handleClickAddBookToReadingList(book) }}
        >
            Agregar
        </button>

        <a  
            href={`/book/${book.ISBN}`}
            class="py-1 px-3 mr-1 mb-1 text-gray-900 focus:outline-none bg-whit dark:bg-sky-800 rounded-full border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-300 dark:text-white dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
        >
            Ver detalle
        </a>
    </div>
</article>

// pruebas/01-reading-list/Ricky10B/src/components/CardBook.tsx
import { CardBookProps, IISBNProp } from '../interfaces/interfacesComponents'

interface ICardBookProps extends CardBookProps {
  readingList: string[]
  addBookToReadingList: ({ ISBN }: IISBNProp) => void
  removeBookFromReadingList: ({ ISBN }: IISBNProp) => void
}

export function CardBook ({
  book,
  readingList,
  addBookToReadingList,
  removeBookFromReadingList
}: ICardBookProps) {

  const {
    ISBN,
    cover,
    title,
    author,
    synopsis,
    year,
    genre,
    pages
  } = book

  const bookInReadingList = readingList.includes(ISBN)

  return (
    <li className='max-w-[700px] bg-[#1f2937] rounded-md grid grid-rows-[250px_min-content] sm:grid-rows-[330px_min-content] shadow-2xl'>
      <div className={`flex ${bookInReadingList && 'opacity-50 blur-[.5px]'}`}>
        <picture>
          <img src={cover} className='w-[150px] max-w-[150px] h-[250px] max-h-[250px] sm:w-[200px] sm:max-w-[200px] sm:h-[330px] sm:max-h-[330px] block object-cover aspect-square rounded-tl-md' />
        </picture>
        <div className='flex flex-col justify-between sm:grid sm:grid-rows-[96px_1fr_80px] py-[6px] px-3'>
          <h3 className='text-2xl font-bold titleBook'>{title} - {author.name}</h3>
          <p className='my-3 text-gray-300 synopsisBook'>{synopsis}</p>
          <div className='flex flex-col justify-end text-sm'>
            <span className='text-gray-300'>
              <span className='font-bold text-white'>Año: </span>
              {year}
            </span>
            <span className='text-gray-300'>
              <span className='font-bold text-white'>Genero: </span>
              {genre}
            </span>
            <span className='text-gray-300'>
              <span className='font-bold text-white'>Páginas: </span>
              {pages}
            </span>
          </div>
        </div>
      </div>
      <button
        className={`${bookInReadingList ? 'bg-[var(--color-btn-remove-card)]' : 'bg-[var(--color-btn-cards)]'} py-2 rounded-b-md font-medium hover:bg-[var(${bookInReadingList ? 'bg-[var(--color-btn-remove-card-hover)]' : 'bg-[var(--color-btn-cards-hover)]'}`}
        onClick={() =>
          bookInReadingList
            ? removeBookFromReadingList({ ISBN })
            : addBookToReadingList({ ISBN })
        }
      >
        {
          bookInReadingList
          ? 'Sacar de la lista'
          : 'Agregar a la lista'
        }
      </button>
    </li>
  )
}
