// pruebas/01-reading-list/byronjvh/src/components/ReadingList.jsx
import { useContext } from 'react'
import { GlobalContext } from '../context/GlobalContext'
import { CrossIcon, List } from './Icons'
import { useMenu } from '../hooks/useMenu'
import { BookItem } from './BookItem'

export function ReadingList () {
  const { readingList } = useContext(GlobalContext)
  const { menuRef, open, updateOpen } = useMenu()

  return (
    <div ref={menuRef} className=''>
      <button onClick={() => updateOpen(true)} className='relative text-xl text-white p-2 bg-blue-600 rounded-md hover:brightness-125' type='button'>
        <List />
        {
          readingList.length > 0 && (
            <span
              className='text-sm font-semibold text-sky-950 flex justify-center items-center w-6 h-6 absolute -bottom-3 -right-3 rounded-full p-1 bg-sky-200 border-2 border-white'>
                {readingList.length}
              </span>
          )
        }
      </button>
      <div className={`fixed z-20 w-full max-w-[452px] flex flex-col h-screen shadow-card bg-white p-3 top-0 right-0 origin-right duration-200 ease-out transition-transform ${open ? 'scale-x-100' : 'scale-x-0'}`}>
        <button onClick={() => updateOpen(false)} type='button' className='self-end text-3xl mb-4 rounded-full transition-[background-color] duration-200 ease-out hover:bg-sky-200'>
          <CrossIcon />
        </button>
        <p className='text-lg mb-4'>Libros en la lista <span className='px-1 bg-sky-200 rounded-full'>{readingList.length}</span></p>
        <ul className='scroll-sm flex flex-col gap-2 overflow-y-auto scroll-mx-2 pr-1'>
          {
            readingList.length > 0
              ? readingList?.map((obj, i) => (
                <BookItem key={obj.book.ISBN} title={obj.book.title} year={obj.book.year} img={obj.book.cover} genre={obj.book.genre} ISBN={obj.book.ISBN} />
              ))
              : <p>No hay libros en la lista de lectura</p>
          }
        </ul>
      </div>
    </div>
  )
}

// pruebas/01-reading-list/KrlosPK/src/app/library/components/reading-list/reading-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Books } from '../../interfaces/types';

@Component({
  selector: 'library-reading-list',
  templateUrl: './reading-list.component.html',
  styleUrls: ['./reading-list.component.css'],
})
export class ReadingListComponent {
  @Input()
  public readingList: Books[] = [];

  @Output()
  public onRemoveFromReadingList = new EventEmitter<string>();

  public isReadingList: boolean = false;
  toggleReadingList(): void {
    this.isReadingList = !this.isReadingList;
  }
  removeFromReadingList(bookId: string): void {
    this.onRemoveFromReadingList.emit(bookId);
  }
}

<aside class="top-0 left-0 z-10 hidden h-full transition-all md:flex">
  <section
    [ngClass]="{ 'reading-list-overflow': isReadingList }"
    class="min-w-[271px] min-h-screen p-4 bg-secondary-color"
  >
    <h2 class="mb-4 text-xl font-semibold text-center whitespace-nowrap">
      Lista de Lectura
      <span *ngIf="readingList.length > 0"> / </span>
      <span
        [ngClass]="{ active: readingList.length > 0 }"
        *ngIf="readingList.length > 0"
        class="font-semibold min-w-[2ch]"
      >
        {{ readingList.length }}
      </span>
    </h2>

    <h3 *ngIf="readingList.length === 0" class="text-sm opacity-90">
      Aún no hay libros en la lista de lectura
    </h3>

    <div
      class="grid grid-cols-1 gap-2 md:place-items-start place-items-center md:grid-cols-2 md:gap-4"
    >
      <article
        [title]="item.book.title"
        *ngFor="let item of readingList"
        class="relative"
      >
        <button
          (click)="removeFromReadingList(item.book.ISBN)"
          class="absolute top-0 right-0 p-1 transition-colors select-none bg-secondary-color hover:bg-cyan-50 rounded-es-lg"
        >
          <img
            alt="Button to delete"
            height="24"
            src="./assets/icons/x.svg"
            width="24"
          />
        </button>

        <img
          [alt]="item.book.title"
          [src]="item.book.cover"
          class="object-contain last-article-margin"
          height="250"
          width="150"
        />
      </article>
    </div>
  </section>
</aside>

<!-- Responsive Nav -->
<aside
  [ngClass]="{ 'is-reading-list': isReadingList }"
  class="fixed top-0 left-0 z-10 flex h-full transition-all -translate-x-full md:hidden"
>
  <button
    (click)="toggleReadingList()"
    class="absolute flex items-center justify-center gap-1 p-3 transition-colors rounded-r-lg select-none bg-secondary-color md:hidden md:hover:bg-gray-900 left-full w-fit h-fit"
    title="Lista de Lectura"
    type="button"
  >
    <img
      alt="Reading list books"
      height="24"
      class="w-4"
      src="./assets/icons/books.svg"
      width="24"
    />
    <span
      [ngClass]="{ active: readingList.length > 0 }"
      class="font-semibold min-w-[2ch]"
    >
      {{ readingList.length }}
    </span>
  </button>

  <section
    [ngClass]="{ 'reading-list-overflow': isReadingList }"
    class="min-h-screen p-4 bg-secondary-color"
  >
    <h2 class="mb-4 text-xl font-semibold text-center whitespace-nowrap">
      Lista de Lectura
    </h2>

    <h3 *ngIf="readingList.length === 0" class="text-sm opacity-90">
      Aún no hay libros en la lista de lectura
    </h3>

    <div
      class="grid grid-cols-1 gap-2 md:place-items-start place-items-center md:grid-cols-2 md:gap-4"
    >
      <article
        [title]="item.book.title"
        *ngFor="let item of readingList"
        class="relative"
      >
        <button
          (click)="removeFromReadingList(item.book.ISBN)"
          class="absolute top-0 right-0 p-1 transition-colors select-none bg-secondary-color hover:bg-cyan-50 rounded-es-lg"
        >
          <img
            alt="Button to delete"
            height="24"
            src="./assets/icons/x.svg"
            width="24"
          />
        </button>

        <img
          [alt]="item.book.title"
          [src]="item.book.cover"
          class="object-contain last-article-margin"
          height="175"
          width="110"
        />
      </article>
    </div>
  </section>
</aside>
