// pruebas/01-reading-list/genaroibc/src/components/BooksList.tsx
import { component$, type PropFunction } from "@builder.io/qwik"
import type { Book, BookISBN } from "~/types"
import { BookCard } from "./shared/BookCard"

type Props = {
  books: Book[]
  onBookSelect: PropFunction<(BookISBN: BookISBN) => void>
}

export const BooksList = component$(({ books, onBookSelect }: Props) => {
  return (
    <section class="grid grid-cols-[repeat(auto-fill,minmax(min(100%,200px),1fr))] gap-12">
      {books.map(book => (
        <button
          key={book.ISBN}
          onClick$={() => onBookSelect(book.ISBN)}
          class="w-full h-full rounded-md"
        >
          <BookCard {...book} />
        </button>
      ))}
    </section>
  )
})

// pruebas/01-reading-list/fjolme/src/components/BooksList.tsx
import { BookWrapper, type Book } from '../types/types'
import { BookItem } from './BookItem'

interface Props {
  booksWrapper: BookWrapper[],
  onlyAvailablesBooks: boolean,
  addToReadingList: (book: Book) => void,
  removeFromReadingList: (book: Book) => void
}

export const BooksList = ({ booksWrapper, onlyAvailablesBooks, addToReadingList, removeFromReadingList }: Props) => {
  const booksList = onlyAvailablesBooks
    ? booksWrapper.filter(booksWrapper => !booksWrapper.inReadingList)
    : booksWrapper

  if (booksList.length === 0) {
    return (
      <p className='p-4 text-center font-light text-neutral-400'>
        No hay resultados
      </p>
    )
  }

  return (
    <section className='p-4 grid grid-cols-auto-fill-12 gap-8 rounded-b-md overflow-y-auto'>
      {booksList.map(({ book, inReadingList }) => {
        return (
          <BookItem
            key={book.ISBN}
            book={book}
            addToReadingList={addToReadingList}
            removeFromReadingList={removeFromReadingList}
            inReadingList={inReadingList}
          />
        )
      })}
    </section>
  )
}
