// pruebas/01-reading-list/dmiante/lista-libros/src/components/Listbook.tsx
import { styled } from 'styled-components'
import { useBooksContext } from '../context/BooksContext'

export default function Listbook () {
  const { books, addReadingList } = useBooksContext()
  // console.log(books)

  return (
    <ListBooks>
      <ul>
        {
          books.map((book) => (
            <li
              key={book.ISBN}
              onClick={() => { addReadingList(book) }}
            >
              <img
                src={book.cover}
                alt={book.title}
              />
            </li>
          ))
        }
      </ul>
    </ListBooks>
  )
}

const ListBooks = styled.section`
  margin-bottom: 3rem;

  ul {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1.25rem;
    width: 100%;
    border-radius: .4rem;
    transition: all ease-in-out 0.25s;
    background-color: #151716;
    padding: 1rem;
    filter: drop-shadow(0 25px 25px rgb(0 0 0 / 0.50));
  }

  li {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: transform .2s ease-in;

    &:hover {
      transform: scale(1.03);
    }
  }
  
  img {
    height: 100%;
    max-width: 100%;
    border-radius: 0.4rem;
  }
  img:hover {
    /* transition: background 4s, transform 1s; */
    /* transform: scale(1.25); */
    /* transition: background 1s linear; */
  }

`

// pruebas/01-reading-list/Isai-gomez/listBook/src/components/ListBook.vue
<template>
  <div class="container-img" v-for="{ book } in datajson" :key="book.ISBN">
    <div class="wrapper-img-btn">

        <img :src="book.cover" :alt="book.title" />
        <button>Añadir a lista de lectura</button>
    </div>
  </div>
</template>
<script>
import data from "../../../../books.json";
import { ref } from "vue";
export default {
  name: "ListBook",
  setup() {
    const datajson = ref(data.library);
    return {
      datajson,
    };
  },
};
</script>
<style scoped>
img {
  border-radius: 10px;
  width: 100%;
  height: auto;
  box-shadow: 0px 0px 30px #0000;
  
}
.container-img {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
  
}
.wrapper-img-btn{
    display: grid;
    place-content: center;
    grid-template-rows: repeat(min(150px), minmax(150px, 1fr));
    gap: 1rem;
}
button{
    background-color: darkslategray;
    height: 3rem;
    width: 15rem;
    color: white;
border-style: none;
}
</style>
