// pruebas/01-reading-list/iivvaannxx/src/features/library/components/book.svelte
<script lang='ts' context='module'>

  import type { Book } from '$types'
  import { InfoIcon } from '$assets/icons'

</script>

<script lang='ts'>

  // Export all the properties of the Book type.
  export let {

    title, pages, genre,
    cover, synopsis, year,
    ISBN, author

  } = { } as Book

</script>

<div class="relative flex flex-col w-full aspect-cover shadow-sm rounded-xl group">

  <img class="w-full h-full rounded-xl" src={cover} alt={title} />

  <div class='absolute h-full w-full'>
    <div class='h-full w-full bg-black rounded-xl opacity-0 transition-opacity duration-300 group-hover:opacity-40'></div>
  </div>

  <div class='absolute flex items-center justify-center h-full w-full'>

    <button class='w-10 h-10 rounded-full flex items-center justify-center  transition-all duration-300 bg-white opacity-0 group-hover:opacity-100 hover:bg-black hover:text-white'>
      <InfoIcon />
    </button>

  </div>

</div>

// pruebas/01-reading-list/juanigna/app/components/Book.tsx
import Image from "next/image";
import { Book } from "../types";

export default function BookCard({ book, addBookToRead }: { book: Book, addBookToRead: (book: Book) => void }) {
    return (
        <div key={book.title} className="flex flex-col overflow-hidden rounded-lg border bg-gray-700 text-white">
            <div className="h-48 md:h-64 group relative block bg-gray-100">
                <Image src={book.cover} className="absolute inset-0 h-full w-full object-cover object-center" alt={book.title} width={500} height={500} />
            </div>
            <div className="flex flex-1 flex-col items-start p-2 sm:p-4">
                <p>{book.title}</p>
                <button className="p-1 bg-gray-600 rounded-sm mt-2" onClick={() => addBookToRead(book)}>Add to read list!</button>
            </div>
        </div>
    )
}
