// pruebas/01-reading-list/FrM-bot/src/lib/components/header.svelte
<script>
  import BookmarkMenu from './bookmarkMenu.svelte'
  import Link from './link.svelte'	
</script>

<header
  class={"sticky top-0 z-20 p-2 duration-200 main-header"}
  id="main-header"
>
  <nav
    class="w-full flex justify-between items-center z-20 sm:gap-2 gap-2 lg:max-w-[90vw] xl:max-w-screen-content max-w-[95vw] m-auto"
  >
    <Link href="/">Bookie</Link>
    <!-- <ul class='flex gap-2 items-center'>
        <li>
          <InputSearch />
        </li>
      </ul> -->
    <ul>
      <li>
        <BookmarkMenu />
      </li>
    </ul>
  </nav>
</header>

// pruebas/02-bazar-universal/doulovera/components/items/header.tsx
import Link from 'next/link'
import Image from 'next/image'

import SearchBox from '@/components/searchbox'

export function ItemsHeader ({ children }: { children?: React.ReactNode }) {
  return (
    <header className="w-full py-4 bg-brand">
      <div className="w-5/6 max-w-xs mx-auto">
        <section className="flex items-center justify-between mb-4">
          <Link href="/">
            <Image
              src='/bazar-truck.png'
              alt='app logo'
              width={55}
              height={55}
            />
          </Link>
          <SearchBox isMini />
        </section>
        <section>
          {children}
        </section>
      </div>
    </header>
  )
}
