// pruebas/01-reading-list/lace04/book-app/src/components/ReadingList.jsx
import React from 'react';

import { BiSolidMinusSquare } from 'react-icons/bi';

function ReadingList({ books, onRemove }) {
  return (
    <div className='bg-zinc-900 h-full p-4'>
      <h1 className='text-4xl text-center font-bold m-5'>Lista Lectura</h1>
      <div className='text-xl mb-4'>Libros disponibles: {books.length}</div>

      <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3'>
        {books.map((book) => (
          <div
            key={book.ISBN}
            className='bg-zinc-800 m-2 flex flex-col justify-center items-center rounded-md hover:bg-zinc-700 relative'
          >
            <img
              src={book.cover}
              alt={book.title}
              className='w-32 h-28 object-contain mt-4'
            />
            <h3 className='md:text-xs text-center m-4 h-12 '>{book.title}</h3>

            <div className='absolute top-2 right-2'>
              <button onClick={() => onRemove(book)}>
                <BiSolidMinusSquare className='text-red-500 text-2xl' />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default ReadingList;

// pruebas/01-reading-list/jose-gzs/src/components/ReadingList.vue
<script setup>
    import { computed, ref } from 'vue';
    import books from '../assets/books.json'
    import ReadingListBookItem from './ReadingListBookItem.vue'

    const storage = window.localStorage
    const savedReadingList = storage.getItem('readingList') || []

    const readingList = ref([savedReadingList])

    const availableBooks = computed(() => {
        return books.library.filter( el => !readingList.value.includes(el.book.ISBN))
    })

    const readingListBooks = computed(() => {
        return books.library.filter( el => readingList.value.includes(el.book.ISBN))
    })

    function addBookToReadingList(id) {
        readingList.value.push(id)
        storage.setItem('readingList', JSON.stringify(readingList.value))
    }

    function deleteBookFromReadingList(index) {
        console.log("delete "+index)
        readingList.value.splice(index,1)
        storage.setItem('readingList', JSON.stringify(readingList.value))
    }


</script>

<template>
    <h2 class="text-4xl font-bold px-8">{{ availableBooks.length }} libros disponibles</h2>
    <h2 v-if="readingListBooks.length" class="text-3xl font-semibold px-8">{{ readingListBooks.length }} en la lista de lectura</h2>
    <div class="inline-flex items-center justify-center px-8 w-full mt-4">
        <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 mx-auto gap-4">
            <template v-for="book in availableBooks" :key="book.book.ISBN">
                <ReadingListBookItem :book="book.book" @click="addBookToReadingList(book.book.ISBN)"/>
            </template>
        </div>
    </div>

    <hr class="my-8">
    <div class="inline-flex items-center justify-center px-8 w-full mt-4">
        <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 mx-auto gap-4">
            <template v-for="(book,index) in readingListBooks" :key="book.book.ISBN">
                <ReadingListBookItem :book="book.book" @click="deleteBookFromReadingList(index)"/>
            </template>
        </div>
    </div>
</template>
