// pruebas/01-reading-list/FrM-bot/src/lib/components/button.svelte
<script lang="ts">
  import { classNamesJoin } from '$lib/utils/classNamesJoin'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  const variants = {
    text: 'hover:[text-shadow:#FC0_1px_0_10px]',
    transparent:
      'backdrop-blur-[2px] bg-dark-v2/50 hover:bg-dark-v2/80 duration-300 rounded-md h-fit grid place-content-center outline-none',
    default:
      'rounded-md bg-dark-v1 shadow-md hover:shadow-black/30 hover:shadow-lg py-[0.4rem] px-[0.8rem] border-tertiary border duration-300',
    gradient:
      'rounded-md p-[1px] flex w-fit h-fit justify-center items-center after:absolute after:bg-gradient-to-l after:from-secondary after:to-primary after:w-full after:rounded after:h-full after:bottom-0 after:left-0 after:opacity-0 after:duration-300 after:z-0 relative w-fit hover:after:opacity-100 shadow-md border-[1px] border-tertiary bg-dark-v1 hover:shadow-primary/10 duration-300'
  }

  export let variant: keyof typeof variants = 'default'

  export let props = {} as HTMLButtonAttributes

  let className = ''

  export { className as class }

  const classButton = classNamesJoin(className, variants[variant])
</script>

{#if variant.startsWith('gradient')}
  <button class={classButton} {...props} on:click>
    <span class="z-[1] bg-dark-v1 h-full w-full rounded py-[.4em] px-[.8em]">
      <slot />
    </span>
  </button>
{:else}
  <button class={classButton} {...props} on:click>
    <slot />
  </button>
{/if}

// pruebas/01-reading-list/nzkdevsaider/src/components/ui/button.jsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva } from "class-variance-authority";

import { cn } from "/src/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground shadow hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
        outline:
          "border border-input bg-transparent shadow-sm hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

const Button = React.forwardRef(({ className, variant, size, asChild = false, ...props }, ref) => {
  const Comp = asChild ? Slot : "button"
  return (
    (<Comp
      className={cn(buttonVariants({ variant, size, className }))}
      ref={ref}
      {...props} />)
  );
})
Button.displayName = "Button"

export { Button, buttonVariants }
