// pruebas/01-reading-list/genaroibc/src/components/shared/BookCard.tsx
import { component$ } from "@builder.io/qwik"
import type { Book } from "~/types"
import {
  IconBookOutlined,
  IconBookmarkFilled,
  IconBookmarkPlus,
  IconCalendarOutlined
} from "~/components/shared/Icons"

export const BookCard = component$(
  ({ cover, genre, isInReadingList, pages, title, year, author }: Book) => {
    return (
      <article class="aspect-[1/1.6] group hover:shadow-lg transition-transform duration-300 ease-in-out text-white relative bg-black rounded-md">
        <div class="relative overflow-hidden rounded-tl-md rounded-tr-md">
          <BookBadge isInReadingList={isInReadingList} />

          <img
            src={cover}
            alt={title}
            width={300}
            height={500}
            class="brightness-95 grayscale-[0.3] group-hover:grayscale-0 group-hover:brightness-110 transition-all duration-300 aspect-[1/1.4] group-hover:scale-110"
          />

          <ul class="absolute bottom-0 flex items-center justify-between gap-4 w-full py-1.5 px-3 bg-black/60 text-gray-200">
            <li class="whitespace-nowrap truncate max-w-full text-xs flex items-center gap-1">
              <IconBookOutlined /> {pages}
            </li>

            <li class="whitespace-nowrap truncate max-w-full text-xs flex items-center gap-1">
              <IconCalendarOutlined />
              {year}
            </li>
          </ul>
        </div>

        <div class="p-4">
          <h6 class="whitespace-nowrap truncate max-w-full my-2 font-bold text-base text-left">
            {title}
          </h6>

          <p class="whitespace-nowrap truncate max-w-full my-2 font-medium text-sm text-left">
            {author.name}
          </p>

          <span class="whitespace-nowrap truncate px-2 py-1 block mt-4 bg-gray-800 text-gray-400 rounded-xl text-xs w-fit">
            {genre.toLocaleLowerCase()}
          </span>
        </div>
      </article>
    )
  }
)

type BadgeProps = {
  isInReadingList: boolean
}

const BookBadge = component$(({ isInReadingList }: BadgeProps) => {
  return (
    <section
      aria-hidden={true}
      class="bg-black/50 p-2 absolute top-1 right-1 z-20 rounded-full"
    >
      {isInReadingList ? (
        <IconBookmarkFilled size={32} />
      ) : (
        <IconBookmarkPlus size={32} />
      )}
    </section>
  )
})

// pruebas/01-reading-list/foleas/src/components/BookCard/index.tsx
import { useState, useEffect } from "react";
import { textColorAnimationClass } from "../../utils/tailwind";
interface BookCardProps {
  index: number;
  title: string;
  year?: number;
  pages?: number;
  genre?: string;
  imageUrl: string;
  withRemoveBnt?: boolean;
  onClickHandler: () => void;
}

const BookCard = ({
  index,
  title,
  year,
  pages,
  genre,
  imageUrl,
  withRemoveBnt = false,
  onClickHandler,
}: BookCardProps) => {
  const [animationClass, setAnimationClass] = useState<string>(
    "opacity-0 translate-y-2"
  );

  // const delay = `delay-[${(index + 1) * 150}ms]`;

  useEffect(() => {
    setAnimationClass("opacity-1 translate-y-0");
  }, []);
  return (
    <article
      className={`cursor-pointer ${animationClass} rounded-lg shadow-[0_0_10px_-1px] shadow-gray-600 dark:shadow-gray-200 overflow-hidden relative transition ease-in-out duration-300`}
      style={{ transitionDelay: `${(index + 1) * 150}ms` }}
      onClick={onClickHandler}
    >
      {withRemoveBnt && (
        <div className="absolute w-6 h-6 -top-3 -right-3 z-10 bg-white border border-black flex align-center justify-center">
          <span className="font-bold">X</span>
        </div>
      )}
      <figure className="flex h-96 overflow-hidden">
        <img
          className="w-full h-full object-cover transition duration-300 ease-in-out hover:scale-110"
          src={imageUrl}
          alt={title}
        />
      </figure>
      <div
        className={`flex flex-col justify-between h-40 p-5 box-border ${textColorAnimationClass}`}
      >
        <div>
          <h2 className="text-xl font-bold">{title}</h2>
          <h3 className="text-base text-gray-600 dark:text-gray-400 font-bold">
            {genre}
          </h3>
        </div>
        <div className="flex align-center justify-between">
          <p>
            <b>Año: </b>
            {year}
          </p>
          <p>
            <b>Páginas: </b>
            {pages}
          </p>
        </div>
      </div>
    </article>
  );
};

export default BookCard;
