// pruebas/02-bazar-universal/fernandochaza/simple-shop/src/app/items/[id]/page.tsx
import ProductRating from "@/components/ProductRating"
import AddToCartIcon from "@/icons/AddToCartIcon"
import Image from "next/image"
import Data from "../../../data/products.json"

const ProductPage = ({ params }: { params: { id: string } }) => {
  const { id } = params

  const products: Array<Product> = Data.products

  const product = products.find(
    (product) => product.id === Number(id)
  )

  if (!product) return <p>Product not found</p>

  const { title, description, price, rating } = product

  const capitalizedTitle = title[0].toUpperCase() + title.slice(1, -1)

  return (
    <article className="bg-slate-50 grid grid-cols-2 auto-rows-min gap-y-2 gap-x-2 relative w-[316px] h-fit mx-auto px-4 py-4 shadow-[5px_5px_20px_#b0b2b3,-5px_-5px_20px_#ffffff] rounded-3xl">
      <h2 className="col-span-full pl-4 text-2xl font-extrabold w-60 line-clamp-2 overflow-hidden">
        {capitalizedTitle}
      </h2>
      <div className="w-[120px] h-[120px] relative mx-auto row-start-2">
        <Image
          className="absolute object-contain rounded-full border place-self-center"
          src={product.images[0] }
          alt={`Image of ${product.title}`}
          fill={true}
          sizes="(max-width: 576px) 100vw, (max-width: 1200px) 50vw, 33vw"
          priority
        />
      </div>
      <p className="row-start-2 place-self-center line-clamp-4 overflow-hidden max-h-24">
        {description}
      </p>
      <p className="absolute right-4 top-4 text-lg font-extrabold text-slate-800">
        ${price}
      </p>
      <ProductRating rating={rating} className="place-self-center" />
      <button className="absolute right-4 bottom-4 rounded-full w-12 h-12 flex flex-col place-items-center place-content-center shadow-[3px_3px_3px_#b0b2b3,-3px_-3px_3px_#ffffff] active:border active:shadow-none transition-shadow duration-50">
        <AddToCartIcon />
      </button>
    </article>
  )
}

export default ProductPage

// pruebas/02-bazar-universal/diego-gonzales/src/routes/items/[id]/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$, type DocumentHead } from '@builder.io/qwik-city';
import { getRating } from '~/helpers/getRating';
import { type ErrorResponse } from '~/interfaces/error-response.interface';
import type { Product } from '~/interfaces/products-response.interface';

export const useProductLoader = routeLoader$(async ({ params, fail }) => {
  const { id } = params;
  const url = `http://localhost:5173/api/items/${id}`;

  const response = await fetch(url);

  if (!response.ok) {
    const { statusCode, message } = (await response.json()) as ErrorResponse;
    return fail(statusCode, { message });
  }

  const data = (await response.json()) as Product;
  return data;
});

export default component$(() => {
  const product: any = useProductLoader();

  if (product.value.message) {
    return (
      <div>
        <h3>{product.value.message}</h3>
      </div>
    );
  }

  return (
    <div class="h-[calc(100vh-80px)] relative">
      <div class="grid gap-5 justify-center items-center justify-items-center">
        <section class="grid gap-4 grid-cols-[3fr_1fr] justify-center items-center justify-items-center">
          <img
            class="rounded-full object-cover w-48 h-48"
            src={product.value.thumbnail}
            alt="Product"
            width={200}
            height={200}
          />
          <ul class="grid gap-2">
            {product.value.images
              .slice(0, 3)
              .map((image: string, index: number) => (
                <li key={index}>
                  <img
                    class="rounded-full object-cover w-16 h-16"
                    src={image}
                    alt={`Image ${index + 1} for ${product.title}`}
                    width={64}
                    height={64}
                  />
                </li>
              ))}
          </ul>
        </section>

        <section class="text-center">
          <h3 class="text-2xl font-bold">{product.value.title}</h3>
          <div class="flex items-center gap-4">
            <p class="flex flex-col">
              <span class="font-bold">{product.value.price}$</span>
              <span class="text-xs">{product.value.stock} disponibles</span>
            </p>
            <p>{getRating({ rating: product.value.rating })}</p>
          </div>
        </section>

        <section class="max-w-md">
          <p>{product.value.description}</p>
        </section>
      </div>

      <div class="absolute bottom-4 md:static md:mt-10 w-full text-center">
        <button class="btn btn-primary w-full max-w-md">Buy</button>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: 'Product',
  meta: [
    {
      name: 'description',
      content: 'Bazar Online product page',
    },
    {
      name: 'keywords',
      content: 'bazar, online, shopping, ecommerce, store, products, buy, sell',
    },
  ],
};
